  app.controller(
    'appController',[
     '$scope',
     function($scope)
     {
       
       $scope.model={
         showPopus:boolean=false,
         showPoptest:boolean=false,
         resr:boolean=false,
         resi:boolean=false,
         resa:boolean=false,
         ress:boolean=false,
         rese:boolean=false,
         resc:boolean=false,
         resr:boolean=false,
         b1:boolean=false,
         b2:boolean=false,
         b3:boolean=false,
         b4:boolean=false,
         b5:boolean=false,
         b6:boolean=false,
         b7:boolean=false,
         b8:boolean=false,
         b9:boolean=false,
         b10:boolean=false,
         b11:boolean=false,
         b12:boolean=false,
         b13:boolean=false,
        b14:boolean=false,
         b15:boolean=false,
         b16:boolean=false,
         b17:boolean=false,
         b18:boolean=false,
         b19:boolean=false,
         b20:boolean=false,
         b21:boolean=false,
         b22:boolean=false,
         b23:boolean=false,
         b24:boolean=false,
         b25:boolean=false,
         b26:boolean=false,
         b27:boolean=false,
         b28:boolean=false,
         b29:boolean=false,
         b30:boolean=false,
         b31:boolean=false,
         b32:boolean=false,
         b33:boolean=false,
         b34:boolean=false,
         b35:boolean=false,
        b37:boolean=false,
        b38:boolean=false,
        b39:boolean=false,
        b40:boolean=false,
        b41:boolean=false,
        b32:boolean=false,
       }; 
       $scope.rv=0;
        $scope.iv=0;
        $scope.sv=0;
        $scope.av=0;
        $scope.cv=0;
        $scope.ev=0;
        $scope.val="";
        $scope.arr=[];
        $scope.profession="";
        $scope.count = 0;
      $scope.bt1=function(input)
       {
         $scope.rv=$scope.rv+input;
        $scope.b1=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt2=function(input)
       {
         $scope.iv=$scope.iv+input;
        $scope.b2=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt3=function(input)
       {
        $scope.av=$scope.av+input;
        $scope.b3=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt4=function(input)
       {
         $scope.sv=$scope.sv+input;
        $scope.b4=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt5=function(input)
       {
         $scope.ev=$scope.ev+input;
        $scope.b5=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt6=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b6=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt7=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b7=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt8=function(input)
       {
         $scope.av=$scope.av+input;
        $scope.b8=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt9=function(input)
       {
        $scope.b9=true;
        $scope.cv=$scope.cv+input;
        $scope.count=$scope.count+1;
       } 
       $scope.bt10=function(input)
       {
        $scope.ev=$scope.ev+input;
         $scope.b10=true;
         $scope.count=$scope.count+1;
       } 
       $scope.bt11=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b11=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt12=function(input)
       {
        $scope.sv=$scope.sv+input;
        $scope.b12=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt13=function(input)
       {
        $scope.count=$scope.count+1;
        $scope.sv=$scope.sv+input;
        $scope.b13=true;
       } 
       $scope.bt14=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b14=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt15=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b15=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt16=function(input)
       {
        $scope.ev=$scope.ev+input;
        $scope.b16=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt17=function(input)
       {
        $scope.av=$scope.av+input;
        $scope.b17=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt18=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b18=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt19=function(input)
       {
        $scope.ev=$scope.ev+input;
        $scope.b19=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt20=function(input)
       {
        $scope.sv=$scope.sv+input;
        $scope.b20=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt21=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b21=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt22=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b22=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt23=function(input)
       {
        $scope.av=$scope.av+input;
        $scope.b23=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt24=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b24=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt25=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b25=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt26=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b26=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt27=function(input)
       {
        $scope.av=$scope.av+input;
        $scope.b27=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt28=function(input)
       {
        $scope.sv=$scope.sv+input;
        $scope.b28=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt29=function(input)
       {
        $scope.ev=$scope.ev+input;
        $scope.b29=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt30=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b30=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt31=function(input)
       {
         $scope.av=$scope.av+input;
        $scope.b31=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt32=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b32=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt33=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b33=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt34=function(input)
       {
        $scope.sv=$scope.sv+input;
        $scope.b34=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt35=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b35=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt36=function(input)
       {
        $scope.ev=$scope.ev+input;
        $scope.b36=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt37=function(input)
       {
        $scope.rv=$scope.rv+input;
        $scope.b37=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt38=function(input)
       {
        $scope.cv=$scope.cv+input;
        $scope.b38=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt39=function(input)
       {
        $scope.iv=$scope.iv+input;
        $scope.b39=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt40=function(input)
       {
        $scope.sv=$scope.sv+input;
        $scope.b40=true;
        $scope.count=$scope.count+1;
       } 
        $scope.bt41=function(input)
       {
        $scope.av=$scope.av+input;
        $scope.b41=true;
        $scope.count=$scope.count+1;
       } 
       $scope.bt42=function(input)
       {
        $scope.ev=$scope.ev+input;
        $scope.b42=true;
        $scope.count=$scope.count+1;
       } 
       $scope.show=function()
       {
         $scope.model.showPopus= true;
       }
       $scope.tshow=function()
       {
         $scope.model.showPoptest = true;
       }
       $scope.dshow=function()
       {
         $scope.model.showPopus = false;
         $scope.model.showPoptest=false;
       }
  $scope.calculate=function()
       {
        $scope.arr.push({id:'R',value:$scope.rv})
        $scope.arr.push({id:'I',value:$scope.iv})
        $scope.arr.push({id:'A',value:$scope.av})
        $scope.arr.push({id:'S',value:$scope.sv})
        $scope.arr.push({id:'E',value:$scope.ev})
        $scope.arr.push({id:'C',value:$scope.cv})
         var i=0,max=0;
         $scope.model.res=true;
               $scope.arr.sort(function(a,b)
               {
                 return a.value-b.value;
               });
         for(i=0;i<6;i++)
         {
           console.log($scope.arr[i].id,$scope.arr[i].value);
         }
           $scope.val=$scope.arr[5].id;
           $scope.profession=$scope.arr[5].id+$scope.arr[4].id+$scope.arr[3].id;
           if($scope.val=='R')
           {
            $scope.model.resr=true;
           }
           else if($scope.val=='I')
           {
            $scope.model.resi=true;
           }
           else if($scope.val=='A')
           {
            $scope.model.resa=true;

           }
           else if($scope.val=='S')
           {
            $scope.model.ress=true;

           }
           else if($scope.val=='E')
           {
            $scope.model.rese=true;
           }
           else{
            $scope.model.resc=true;
           }
           
      }
    }
]);